changelog:
  categories:
    - title: ✨ Features
      labels: [feat, feature]
    - title: 🐛 Fixes
      labels: [fix, bug]
    - title: 📚 Documentation
      labels: [docs, documentation]
    - title: ♻️ Refactoring
      labels: [refactor]
    - title: 🧪 Tests
      labels: [test, tests]
    - title: 🔧 Maintenance
      labels: [chore, ci, build]
    - title: ⬆️ Dependencies
      labels: [dependencies]
