name: Auto-Fix Failing Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, development]
  workflow_dispatch:

jobs:
  test-and-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # Install Nova CI-Rescue
          pip install nova-ci-rescue

      - name: Run tests
        id: test
        continue-on-error: true
        run: |
          pytest tests/ -v --tb=short --junit-xml=test-results.xml
          echo "test_exit_code=$?" >> $GITHUB_OUTPUT

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml

      - name: Auto-fix with Nova
        if: steps.test.outputs.test_exit_code != '0'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NOVA_ENABLE_TELEMETRY: true
          NOVA_DEFAULT_LLM_MODEL: gpt-5-chat-latest
        run: |
          echo "🔧 Tests failed! Running Nova CI-Rescue to auto-fix..."

          # Configure git
          git config --global user.name "Nova CI Bot"
          git config --global user.email "nova-bot@example.com"

          # Run Nova with whole-file mode
          nova fix . --whole-file --max-iters 5 --timeout 600

          # Check if Nova created a fix branch
          if git branch -r | grep -q "nova-auto-fix"; then
            echo "✅ Nova created a fix branch"
            
            # Create PR with the fix
            gh pr create \
              --title "🤖 Auto-fix: Resolve failing tests" \
              --body "This PR was automatically generated by Nova CI-Rescue to fix failing tests.
              
              ## Summary
              - Fixed failing algorithm implementations
              - All tests now pass
              
              Please review the changes carefully before merging." \
              --base ${{ github.base_ref || 'main' }} \
              --head nova-auto-fix/$(date +%Y%m%d_%H%M%S)
          else
            echo "❌ Nova could not create a fix"
            exit 1
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.test.outputs.test_exit_code != '0'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Nova CI-Rescue Report**\n\nI detected failing tests and attempted to fix them automatically. Please check the auto-fix PR for the proposed changes.'
            })
