name: Nova Demo CI Tests

on:
  push:
    branches: [main, demo]
  pull_request:
    branches: [main, demo]
  workflow_dispatch:

jobs:
  nova-basic-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Make scripts executable
        run: |
          chmod +x setup_nova.sh
          chmod +x test_nova.sh
          chmod +x test_nova_verbose.sh

      - name: Run Nova Basic Test
        id: nova-basic
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "::group::Running Nova Basic Test"
          ./test_nova.sh
          echo "::endgroup::"
          echo "test_passed=true" >> $GITHUB_OUTPUT

  nova-verbose-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Make scripts executable
        run: |
          chmod +x setup_nova.sh
          chmod +x test_nova.sh
          chmod +x test_nova_verbose.sh

      - name: Run Nova Verbose Test
        id: nova-verbose
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "::group::Running Nova Verbose Test"
          ./test_nova_verbose.sh
          echo "::endgroup::"
          echo "test_passed=true" >> $GITHUB_OUTPUT

  summary:
    needs: [nova-basic-test, nova-verbose-test]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Create summary
        run: |
          echo "## Nova Demo Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "### Test Status:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Nova Basic Test: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Nova Verbose Test: Completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "### What was tested:" >> $GITHUB_STEP_SUMMARY
          echo "1. **Basic Test**: Nova automatically fixed a bug in calculator.py (subtraction method)" >> $GITHUB_STEP_SUMMARY
          echo "2. **Verbose Test**: Nova fixed a validation bug in string_utils.py (truncate_string method)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "Both tests demonstrate Nova's ability to:" >> $GITHUB_STEP_SUMMARY
          echo "- Identify failing tests" >> $GITHUB_STEP_SUMMARY
          echo "- Analyze the code and understand the bug" >> $GITHUB_STEP_SUMMARY
          echo "- Generate and apply appropriate fixes" >> $GITHUB_STEP_SUMMARY
          echo "- Verify the fixes work correctly" >> $GITHUB_STEP_SUMMARY
